[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.5"
  NODE_ENV = "production"
  VITE_API_URL = "https://mybarber-backend-production.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
