[build]
  command = "npm ci && npx vite build"  # Ensures clean install and build using Vite
  publish = "dist"  # Output folder for the build artifacts
  base = "/"  # Base directory for the build

[build.environment]
  NODE_VERSION = "18"  # Use Node.js 18 for compatibility

[dev]
  framework = "vite"  # Specify Vite as the framework for local development
  targetPort = 3000  # Ensure local server runs on the correct port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  # Redirect all routes to index.html for a SPA

[context.production.environment]
  NODE_ENV = "production"  # Set the environment variable for production
  VITE_API_URL = "https://mybarber-backend-production.up.railway.app"  # Backend API URL
